### ISSUE TITLE
Some sort of collection display issue (possibly related to pagination)

### ISSUE THREAD

**Issue by eweidenh** [mikethicke/wp-museum#81]
![image](https://user-images.githubusercontent.com/98735604/151759592-1737796e-1770-4968-8523-aaf9f2b9417d.png)

This is on Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by mikethicke** [comment]
Typo enqueueing frontend block styles addressed by a14e35c0d490bd01d3ce0ac14efda23c58fc5dce
