### ISSUE TITLE
Main image representing a given collection is taken from the entry being viewed (main UTSIC site)

### ISSUE THREAD

**Issue by eweidenh** [mikethicke/wp-museum#82]
![image](https://user-images.githubusercontent.com/98735604/151760510-506d8383-bf85-4139-a1cd-7fb1682bb624.png)

I'm not sure whether this is a bug or an unimplemented feature. I don't recall whether we are able to select a main image for a collection.

**Comment by mikethicke** [comment]
I don't see this behavior on the site. Possibly it was corrected earlier?
