### ISSUE TITLE
Menu bar disappears when the site is not maximized (at a certain width)

### ISSUE THREAD

**Issue by eweidenh** [mikethicke/wp-museum#91]
When the width of the catalogue window is reduced past a certain width, the menu bar disappears.

![image](https://user-images.githubusercontent.com/98735604/193750019-967a43f4-90bd-42d2-8194-607330f00f6f.png)

vs...

![image](https://user-images.githubusercontent.com/98735604/193750217-93683986-9745-4e02-b236-a19c25a72749.png)

This happens when the Instagram and Twitter buttons intersect the main title text. Since that text is long, this might be an issue for some devices/ smaller screens.

**Comment by mikethicke** [comment]
When the window goes below a certain width, the top menu turns into a hamburger menu (upper right) that opens to the side:

<img width="936" alt="Screen Shot 2022-12-18 at 10 05 51 AM" src="https://user-images.githubusercontent.com/26980498/208305724-ce8c7a96-7d48-4abe-9cda-894710d525c4.png">
