### ISSUE TITLE
Clicking an artifact "edit" link on a collections editing page brings you to the "All Posts" lists

### ISSUE THREAD

**Issue by eweidenh** [mikethicke/wp-museum#94]
"view" functions as it should

![image](https://user-images.githubusercontent.com/98735604/199132554-1c706ed2-692c-4cca-a612-7aa471eae42f.png)

**Comment by mikethicke** [comment]
For some reason this doesn't manifest either in my local development environment or on the utsic.mikethicke.com testing site.

The [get_edit_post_link](https://developer.wordpress.org/reference/functions/get_edit_post_link/) function encodes the '&' by default, which seems like the cause of the problem.

https://github.com/mikethicke/wp-museum/commit/6136d391865c0237615a2ab5a92e85a1f0c1757e changes the context of get_edit_post_type to 'link'.

I believe this will address the issue, though I can't test it as it doesn't manifest on my machines.
